### ISSUE TITLE
Limiting to a specific animal type

### ISSUE THREAD

**Issue by kingkobra87** [ParamITNL/fs22-AnimalHelperMod#14]
Is there a way to specify feeding only one or two animal types instead of all of them? For instance, only allowing sheep or cows to "graze" for grass, but still needing to do the rest of the work manually. I've been messing around with the script all day, but I just can't seem to figure it out. I'm not too knowledgeable in LUA, but I feel like I'm overlooking something that should be relatively simple.

Thanks in advance

**Comment by ParamITNL** [comment]
Filtering on "type of animal" should not be too hard, and can be done in the method "runHelpers". There is a line, selecting the helper based on the AnimalTypeName:

local helper = Utils.getNoNil(AnimalHelper.helpers[clusterHusbandry.animalTypeName], AnimalHelper.helpers.DEFAULT);

By adding a helper, in the top of the script for the animals you don't want to be taken care of that simply does nothing, this should be achievable. 

Say, you want to do the cows yourself, you could do something like this (No guarantee, haven't tested this, but this should work):

AnimalHelper = {
    helpers = {
        ["HORSE"] = function(husbandry, farmId)
            return AnimalHelper:doForHorseHusbandry(husbandry, farmId);
        end,
        **["COW"] = function(husbandry, farmId)
            return 0
        end,**
        ["DEFAULT"] = function(husbandry, farmId)
            printdbg("running default helper...");
            return AnimalHelper:doForHusbandry(husbandry, farmId);
        end
    },
    enabled = false,
    isDebug = true,
    fillStraw = true,
    modName = g_currentModName,
    modDir = directory,
    startHour = 9
}

Hope this helps you out.

**Comment by kingkobra87** [comment]
This is perfect! Just tested, and it's working exactly as intended. Thank you very much! Your help is greatly appreciated.
