### ISSUE TITLE
I want this script but I can't take it

### ISSUE THREAD

**Issue by Zaki03728** [ParamITNL/fs22-AnimalHelperMod#18]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Mod Version [e.g. 22]
 - Game Version [e.g. 1.2.0.2]
 - Other mods installed/in use in savegame

**Additional context**

**Comment by ParamITNL** [comment]
I'll need more info on what the problem is
